POST http://localhost:8080/api/v1/categories
Content-Type: application/json
Authorization: Bearer

{
  "name": "CARS",
  "description": "Cars and automotive"
}

###

PUT http://localhost:8080/api/v1/categories/e8ec0243-c2e6-4f47-8bfe-f2098a326f0a
Content-Type: application/json
Authorization: Bearer

{
  "name": "Möbels",
  "description": "Furnitures and home decors"
}

###

GET http://localhost:8080/api/v1/categories/e8ec0243-c2e6-4f47-8bfe-f2098a326f0a

###
DELETE http://localhost:8080/api/v1/categories/e8ec0243-c2e6-4f47-8bfe-f2098a326f0a
Content-Type: application/json
Authorization: Bearer


